# Generated by Django 4.2.5 on 2023-10-20 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
